import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Montserrat } from 'next/font/google';
import { Josefin_Sans } from 'next/font/google';
import Header from './components/Header/Header';
import Logo from './components/Logo/Logo';
import '../styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});
const josefin_sans = Josefin_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefin_sans.className}>
        <Header />
        <Logo />
        {children}
      </body>
    </html>
  );
}
