import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import { Montserrat } from 'next/font/google';

import Header from '../components/Header/Header';
import Logo from '../components/Logo/Logo';

import '../../styles/globals.scss';
import Footer from '../components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: 'fr' | 'en';
  };
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={montserrat.className}>
        <Header />
        {/* <Logo /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
